require("@rails/ujs").start();
require("turbolinks").start();
require("@rails/activestorage").start();
require("channels");
require("jquery");
global.$ = jQuery;
require("popper.js");
require("bootstrap");
require("packs/posts");
require("packs/notifications");
require("packs/comments");
require("packs/search_users");
